### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by SirElismyer** [fredvs/strumpract#1]
Issue: While in DJ layout clicking the number indication on the input channel throws an exception of "Access Violation".
Repeatable: Yes
Version: 64 bit linux on Linux Mint 19 Xfce
![screenshot_2018-12-25_18-46-12](https://user-images.githubusercontent.com/23237970/50427424-9e354d80-0875-11e9-9c1b-9dfe1984a007.png)

**Comment by fredvs** [comment]
Hello.

Thanks to note this.

I will check it asap.

Write you later.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

I did try to reproduce the error but without luck.

> clicking the number indication on the input channel 

Sorry but I do not understand, what is the **_number indication on the input channel_** ?

On what window is it ?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Re-re-re hello.

Yep, I did have find what you noted.

OK, I will check this tonight and fix it.

Thanks.

**Comment by fredvs** [comment]
OK, fixed.

There is new release with fixes:
https://github.com/fredvs/strumpract/releases/tag/1.8.1

Many thanks to note this.

Fre;D

**Comment by fredvs** [comment]
No tears so I close the issue.
