### ISSUE TITLE
Image dancer

### ISSUE THREAD

**Issue by lainz** [fredvs/strumpract#5]
Check this:
https://forum.lazarus.freepascal.org/index.php/topic,51731.0.html

Maybe you can use that code to do another image dancer.

**Comment by fredvs** [comment]
Excellent!

Do you think it is mpossible to use it for MSEgui?
Is it possible to have the same result without BGRAVirtualScreen (because it is not enabled yet for MSEgui)?

What code should I use, yours or from winni?

Many thanks.

Fre;D

**Comment by lainz** [comment]
Yes is possible, there is no difference.

You can use the one you want. I think winni is better since it has random drawings.

**Comment by fredvs** [comment]
> Yes is possible, there is no difference.

Ha ok (so I dont understand the goal of VirtualScreen)

>  I think winni is better since it has random drawings.

Hum, my dancer has to follow the music and the tempo.
I am not sure random makes good dancers.

;-)

OK, I will try both code and replace random with beat.

Write you later.

Fre;D

**Comment by lainz** [comment]
Well VirtualScreen can discard just a portion of the area and keep the other portion if needed. As well now works with retina display on macOS.

Is just handy to have the event handler with a BGRABitmap image already instantiated, as well it is resized automatically.

I think I don't forget nothing, but is basically that. In real code you save some lines of code like the resampling (call to setsize when window size changes).

**Comment by fredvs** [comment]
Hello.

Ok, there is a atom dancer in last commit.

![dancer_atom](https://user-images.githubusercontent.com/3421249/95795626-1ab74b80-0ceb-11eb-853b-ba3386943362.png)

Video and audio of Atom Dancer in action:
[image_dancer_atom.mp4.zip](https://github.com/fredvs/strumpract/files/5367928/image_dancer_atom.mp4.zip)

**Comment by fredvs** [comment]
Here video of last commit with zooming:

[image_dancer_atom2.mp4.zip](https://github.com/fredvs/strumpract/files/5368102/image_dancer_atom2.mp4.zip)

**Comment by lainz** [comment]
Wow looks amazing =)

**Comment by fredvs** [comment]
Thanks (to BGRABitmap) !

**Comment by fredvs** [comment]
Hello.

There is Spiral Dancers of Winni.

![Capture d’écran_2020-10-16_14-05-20](https://user-images.githubusercontent.com/3421249/96265621-f054df00-0fc5-11eb-8a01-b89d884d80c5.png)

I have to say it is very impressing while dancing.

Here video in action:
[image_dancer_spiral.mp4.zip](https://github.com/fredvs/strumpract/files/5391978/image_dancer_spiral.mp4.zip)
